[project]
name = "rock-book"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "openpyxl>=3.1.5",
    "pandas>=3.0.5",
    "requests>=2.34.2",
    "uvicorn>=0.52.1",
]

[[tool.uv.index]]
url = "https://mirrors.ustc.edu.cn/pypi/simple"
default = true
